package com.amum.test;

public class SplitStockRun {

	public static void main(String[] args) {
		String line="A2ZINFRA, ABMINTLTD, AKSHOPTFBR, ALCHEM, ANIKINDS, ARSSINFRA, ASAL, BALAJITELE, BALKRISHNA, BANSWRAS, BEPL, BIGBLOC, BIRLAMONEY, BPL, BRIGADE, CENTRALBK, CIMMCO, CREST, DCM, ELECTCAST, EUROTEXIND, GILLANDERS, GOLDINFRA, GREENPOWER, GTNIND, GTNTEX, GULPOLY, HDFC, HINDDORROL, HIRECT, HMT, HUSYSLTD, ITDCEM, JAIBALAJI, JKPAPER, JMFINANCIL, KABRAEXTRU, KANANIIND, KAVVERITEL, KEC, KOHINOOR, KOKUYOCMLN, KOTHARIPET, LIBAS, M100, MALUPAPER, MANAKCOAT, MANAPPURAM, MANGCHEFER, MSPL, NAGAFERT, NAGREEKCAP, NBVENTURES, NDL, NIBL, NITINSPIN, NTPC, OMMETALS, ONELIFECAP, ONWARDTEC, ORIENTALTL, ORIENTPPR, ORTEL, PDMJEPAPER, PDUMJEPULP, PERFECT, PNCINFRA, PRECOT, PRESTIGE, RAMANEWS, RECLTD, RUCHIRA, SCHNEIDER, SICAGEN, SMCSRVIRG, SUPERSPIN, SYNDIBANK, TECHNOFAB, TREEHOUSE, VARDHACRLC, WEIZMANIND, WELENT, WELINV, XPROINDIA, ZEEL";
		String input[]=line.split("\\s*,\\s*");
		for(int i=0;i<input.length;i++){
			System.out.println("finalGoodStock.add(\""+input[i]+"\");");
		}

	}

}
