package com.amum.testresult;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.HashSet;
import java.util.Properties;
import java.util.Set;

import com.amum.atr.AverageTrueRangePattern;
import com.amum.sma.SimpleMovAvgPattern;
import com.amum.util.AmumUtil;
import com.amum.util.CommonLogicImplementation;
import com.amum.vwap.VolWeightedAvgPricePattern;

public class AmumTestEngine {

	public static void main(String[] args) throws IOException {
		System.out.println("Execution Started......");
		long startTime = System.currentTimeMillis();
		
		Properties prop = new Properties();
		InputStream input = null;
		input = new FileInputStream("conf/config.properties");
		prop.load(input);
		
		/*
		 * Executing stock aginst the Input file
		 */
		AverageTrueRangePattern.execute();
		SimpleMovAvgPattern.execute();
		VolWeightedAvgPricePattern.execute();
		/*
		 * Pick the Good stock from the file generated by above methods
		 */
		Set<String> finalGoodStock = new HashSet<>();
		Set<String> atrStock = CommonLogicImplementation.getGoodStockFrmAtr(prop,prop.getProperty("atr.summary.name"));
		System.out.println("ATR==>"+atrStock);
		finalGoodStock.addAll(atrStock);
		Set<String> smaStock =CommonLogicImplementation.getGoodStockFrmSma(prop,prop.getProperty("sma.summary.name"));
		System.out.println("SMA==>"+smaStock);
		finalGoodStock.addAll(smaStock);
		/*Set<String> vwapStock =CommonLogicImplementation.getGoodStockFrmVwap(prop,prop.getProperty("vwap.summary.name"));
		System.out.println("VWAP==>"+vwapStock);
		finalGoodStock.addAll(vwapStock);*/
		System.out.println("Final Good Stock ==> "+finalGoodStock);
		
		CommonLogicImplementation.getGoodStockForThirtyMin(prop,finalGoodStock);
		AmumUtil.executionTime(startTime);
		System.out.println("Execution Completed......");
	}

}
